bracket = {
    "East": {
        1: "Duke",
        2: "Illinois",
        3: "Alabama",
        4: "Texas Tech",
        5: "St. John's",
        6: "North Carolina",
        7: "Saint Mary's",
        8: "Kentucky",
        9: "N.C. State",
        10: "UCF",
        11: "Saint Louis",
        12: "Yale",
        13: "UNC Wilmington",
        14: "North Dakota St.",
        15: "Central Arkansas",
        16: ["LIU", "Bethune Cookman"],
    },
    "Midwest": {
        1: "Michigan",
        2: "Connecticut",
        3: "Iowa St.",
        4: "Vanderbilt",
        5: "Louisville",
        6: "Wisconsin",
        7: "Georgia",
        8: "Iowa",
        9: "Texas",
        10: "TCU",
        11: ["Stanford", "VCU"],
        12: "Miami OH",
        13: "Liberty",
        14: "Navy",
        15: "Wright St.",
        16: ["UMBC", "Howard"],
    },
    "South": {
        1: "Florida",
        2: "Houston",
        3: "Purdue",
        4: "Nebraska",
        5: "Kansas",
        6: "Tennessee",
        7: "Miami FL",
        8: "Ohio St.",
        9: "Utah St.",
        10: "Texas A&M",
        11: "South Florida",
        12: "Northern Iowa",
        13: "Stephen F. Austin",
        14: "East Tennessee St.",
        15: "Troy",
        16: "Tennessee St.",
    },
    "West": {
        1: "Arizona",
        2: "Michigan St.",
        3: "Virginia",
        4: "Gonzaga",
        5: "Arkansas",
        6: "BYU",
        7: "Villanova",
        8: "Clemson",
        9: "UCLA",
        10: "Santa Clara",
        11: ["Missouri", "SMU"],
        12: "High Point",
        13: "Utah Valley",
        14: "UC Irvine",
        15: "Portland St.",
        16: "Merrimack",
    },
}
